### ISSUE TITLE
Minimal synchronous script problem

### ISSUE THREAD

**Issue by Cracert** [agrimgt/python-fieldclimate#1]
Running sample synchronous script on recent version (1.2) 

```
from fieldclimate import FieldClimateClient

if __name__ == '__main__':
    client = FieldClimateClient(private_key='xxx, public_key='yyy')
    client.get_user()
```
raises this error:

```
...
File "/home/robert/miniconda3/envs/fieldclimate/lib/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
``` 

What can be the reason?

**Comment by wizpig64** [comment]
Sorry for the late reply! Need to turn on notifications for my own repository I guess.

get_user() internally opens and closes an asyncio event loop if you're running it with the synchronous syntax. Maybe there's some other code opening a loop that you're not aware of? Personally I have not tested this (or anything) with miniconda, maybe that is the issue. 

Using it in a fresh environment works for me: 

```
$ pyenv virtualenv 3.6.8 fc
(fc) $ pip install python-fieldclimate
(fc) $ python << EOF
from fieldclimate import FieldClimateClient
client = FieldClimateClient(public_key="x", private_key="y")
print(client.get_user())
EOF
{'message': 'Unauthorized. The request requires user authentication, refer to documentation for more information.'}
```

**Comment by Cracert** [comment]
Thank you for reply and your explanation. I will check it.
