### ISSUE TITLE
Javascript support?

### ISSUE THREAD

**Issue by dkati** [agrimgt/python-fieldclimate#3]
good evening. i didnt manage to make javascript fetch data from the API.
any chance to make it work ?

For now , i got this code:

```

	var pub_key = "xxx";
        var priv_key = "yyy";
 	  
	var dateStamp = "Fri, 03 Jan 2020 21:57:10 GMT";
	var content = "GET"+"/user"+dateStamp+pub_key;
	var hash = CryptoJS.HmacSHA256(content, priv_key);
	//var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

	var tmpstr=hash+"";

	var authStr =  "hmac " + pub_key +":" + tmpstr;
      let API_LINK = "https://api.fieldclimate.com/v1/user";
	console.log("=============");
	console.log("hmac "+pub_key+":"+tmpstr);
      fetch(API_LINK, {
        method: "GET",
        headers: {
		"Accept":"application/json",
		"Authorization":authStr
		
	}
      })
       //response => response.ok ? response.json() : Promise.reject(response)
      .then(response => {console.log(response)})
      .then(data => {console.log(data)})
      .catch( error => {console.log(error)})
	
```

But i get 401 response code :/

**Comment by wizpig64** [comment]
Hi dkati, I hope you had a good weekend.

It looks like you aren't providing the "Date" header, which I believe also needs to be included.

    headers: {
    	"Accept":"application/json",
    	"Date": dateStamp,
    	"Authorization":authStr
    }

If that does not work.... Here's the test I wrote (in python) where I make sure the correct headers are set. If you set your keys and datestamp to the ones in this test, and your authStr comes out to be exactly like mine here, then I see no reason why your code would fail:

https://github.com/agrimgt/python-fieldclimate/blob/master/tests/test_client.py#L85-L89

Good luck :)

**Comment by dkati** [comment]
```
debugfun(){
	
	var pub_key = "xxx";
        var priv_key = "yyyy";
 	  
	var dateStamp = "Fri, 03 Jan 2020 21:57:10 GMT";
	var content = "GET"+"/user"+dateStamp+pub_key;
	var hash = CryptoJS.HmacSHA256(content, priv_key);
	//var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

	var tmpstr=hash+"";

	var authStr =  "hmac " + pub_key +":" + tmpstr;
      let API_LINK = "https://api.fieldclimate.com/v1/user";
	console.log("=============");
	console.log("hmac "+pub_key+":"+tmpstr);
      fetch(API_LINK, {
        method: "GET",
        headers: {
		"Accept":"application/json",
		"Date":dateStamp,
		"Authorization":authStr
		
	}
      })
       //response => response.ok ? response.json() : Promise.reject(response)
      .then(response => {console.log(response)})
      .then(data => {console.log(data)})
      .catch( error => {console.log(error)})
	
	  
	}
```
i still get 401....i think i cant append Date to header due to security reasons.

My python scripts and my java execs works perfectly

**Comment by wizpig64** [comment]
You're calculating the hash correctly from what I can tell, but the dateStamp you're using is still back from the 3rd. Not sure what you mean by security reasons.

Why don't you try creating your dateStamp at runtime? This one method should format it correctly:

    > (new Date()).toUTCString()
    'Mon, 06 Jan 2020 19:24:01 GMT'

**Comment by dkati** [comment]
```
debugfun(){
	
	var pub_key = "xxx";
        var priv_key = "yyy";
 	  
	var dateStamp =  (new Date()).toUTCString();
	var content = "GET"+"/user"+dateStamp+pub_key;
	var hash = CryptoJS.HmacSHA256(content, priv_key);
	//var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);

	var tmpstr=hash+"";

	var authStr =  "hmac " + pub_key +":" + tmpstr;
      let API_LINK = "https://api.fieldclimate.com/v1/user";
	console.log("=============");
	console.log("hmac "+pub_key+":"+tmpstr);
      fetch(API_LINK, {
        method: "GET",
        headers: {
		"Accept":"application/json",
		"Date":dateStamp,
		"Authorization":authStr
		
	}
      })
       //response => response.ok ? response.json() : Promise.reject(response)
      .then(response => {console.log(response)})
      .then(data => {console.log(data)})
      .catch( error => {console.log(error)})
	
	  
	}
```
Tried that way and i still get 401

**Comment by wizpig64** [comment]
OK I tried to get your code working in my node CLI. This gets me a 200 with my real production keys:

Bash:

	$ npm install node-fetch crypto-js
	$ node --version
	v13.5.0
	$ FIELDCLIMATE_PUBLIC_KEY=xxx FIELDCLIMATE_PRIVATE_KEY=yyy node

Node:

	const CryptoJS = require("crypto-js");
	const fetch = require("node-fetch");
	
	function debugfun(){
		var pub_key = process.env.FIELDCLIMATE_PUBLIC_KEY;
		var priv_key = process.env.FIELDCLIMATE_PRIVATE_KEY;
		var dateStamp =  (new Date()).toUTCString();
		var method = "GET"
		var path = "/user"
		var content = method + path + dateStamp + pub_key;
		var hash = CryptoJS.HmacSHA256(content, priv_key);
		var authStr =  "hmac " + pub_key +":" + hash;
		let API_LINK = "https://api.fieldclimate.com/v1" + path;
		fetch(API_LINK, {
			method: method,
			headers: {
				"Accept": "application/json",
				"Date": dateStamp,
				"Authorization": authStr
			}
		})
		//response => response.ok ? response.json() : Promise.reject(response)
		.then(response => {console.log(response)})
		.then(data => {console.log(data)})
		.catch( error => {console.log(error)})
	}
	debugfun()

If you can't get it to authorize, all i can say at this point is double check your keys or contact metos support.

BTW, I suggest you might try the `axios` library instead of fetch, as in my experience it has a little more friendly of an interface than fetch.

**Comment by dkati** [comment]
i use apache localhost way, with CDN scripts...not node js :/ i will try that

**Comment by dkati** [comment]
here is my new code:
```
	var pub_key = "xx";
        var priv_key = "yy";
	var dateStamp =  (new Date()).toUTCString();
	var method = "GET"
	var path = "/user"
	var content = method + path + dateStamp + pub_key;
	var hash = CryptoJS.HmacSHA256(content, priv_key);
	var authStr =  "hmac " + pub_key +":" + hash;
	let API_LINK = "https://api.fieldclimate.com/v1" + path;

	const options = {
  		headers: {"Accept": "application/json",
	 		"Date": dateStamp,
	 		"Authorization": authStr}
	};
	axios.get(API_LINK,options)	
	.then (response => {console.log(response)})
	  
	}
```
i get a log :
**Attempt to set a forbidden header was denied: Date**

same with 
XMLHttpRequest

Removing that header, give me 401 again...

PS
I remind: on java and python it works nicely (i also add Date header there)

**Comment by wizpig64** [comment]
I installed axios and pasted your updated code into my setup, and it works nicely for me:

```
> debugfun()
undefined
> {
  status: 200,
  statusText: 'OK',
  headers: {
    server: 'nginx/1.10.0',
    date: 'Mon, 06 Jan 2020 20:43:59 GMT',
    'content-type': 'application/json',
    'content-length': '634',
    connection: 'close',
    vary: 'Accept-Encoding',
    'x-powered-by': 'PHP/7.0.22',
    'access-control-allow-methods': 'GET,PUT,DELETE',
    'access-control-allow-headers': 'Accept, Accept-Language, Authorization, Date, Request-Date, Version, Content-Type',
    'access-control-allow-origin': '*'
  },
  config: {
    url: 'https://api.fieldclimate.com/v1/user',
    method: 'get',
    headers: {
      Accept: 'application/json',
      Date: 'Mon, 06 Jan 2020 20:43:58 GMT',
      Authorization: 'hmac XXXXX:81514ee586638e94d1f904743bfd4cb06597bc76ce104259405b61d36b1e7c18',
      'User-Agent': 'axios/0.19.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'api.fieldclimate.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.fieldclimate.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 1004,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /v1/user HTTP/1.1\r\n' +
      'Accept: application/json\r\n' +
      'Date: Mon, 06 Jan 2020 20:43:58 GMT\r\n' +
      'Authorization: hmac XXXXX:81514ee586638e94d1f904743bfd4cb06597bc76ce104259405b61d36b1e7c18\r\n' +
      'User-Agent: axios/0.19.0\r\n' +
      'Host: api.fieldclimate.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    path: '/v1/user',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.fieldclimate.com/v1/user',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.fieldclimate.com/v1/user',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      date: [Array],
      authorization: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  data: {
    username: 'XXX',
    info: {  XXX  },
    company: {  XXX  },
    address: {  XXX  },
    settings: { language: 'da', unit_system: 'metric' },
    create_time: '2014-XXX',
    last_access: '2020-01-06 20:43:59',
    sync_disabled: true,
    created_by: 'FieldclimateNG',
    terms_accepted: true,
    newsletter: { technical: true, promotional: true },
    customizations: []
  }
}
```

As you say, removing the date header gave me `Request failed with status code 401`. It could be your particular browser forbidding you from setting it, or something else, I'm not sure.

**Comment by dkati** [comment]
i use latest mozilla and chrome. both failed...

How do u run it ?

**Comment by wizpig64** [comment]
I'm running it in a node js command line, which avoids the browser altogether.

In my bash terminal (i'm using linux, but [a windows command prompt or powershell should work fine](https://treehouse.github.io/installation-guides/windows/node-windows.html)), where I already have node.js installed, I installed axios and js-crypto with `npm`, and ran `node`:

	$ npm install axios crypto-js
	$ node

this switched from bash to a node terminal, where I pasted this (with my keys fixed):

	const CryptoJS = require("crypto-js");
	const axios = require("axios");

	function debugfun () {
		var pub_key = "xxx";
		var priv_key = "yyy";
		var dateStamp =  (new Date()).toUTCString();
		var method = "GET";
		var path = "/user";
		var content = method + path + dateStamp + pub_key;
		var hash = CryptoJS.HmacSHA256(content, priv_key);
		var authStr =  "hmac " + pub_key + ":" + hash;;
		var API_LINK = "https://api.fieldclimate.com/v1" + path;
		const options = {
			headers: {
				"Accept": "application/json",
				"Date": dateStamp,
				"Authorization": authStr
			}
		};
		axios.get(API_LINK,options)
		.then(response => {console.log(response)});
	}
	debugfun()

**Comment by wizpig64** [comment]
I did some googling and found that apparently setting `Date` is not allowed by browsers, as this is part of the http request standard: https://stackoverflow.com/a/36037501

This restriction must not be implemented in node.js :\

**Comment by dkati** [comment]
yea but a client is using a browser..not a node.js :/

**Comment by wizpig64** [comment]
I doubt this is the right final solution, but you could make your own intermediary server to talk to their server with the appropriate keys. so your client talks to your server, which adds the appropriate headers and talks to their server, and hands the response back. If you don't already have that kind of server set up or planned (like I did in the project I originally needed python-fieldclimate for), this might not be the right way to go. 

fieldclimate themselves use js for ng.fieldclimate.com, so it must be possible. I just logged into that site, and their API requests being sent there *do not* have Date set, oddly enough. You should contact their support and ask how they do it. They are friendly and may be able to hook you up with a dev of theirs.

**Comment by wizpig64** [comment]
@dkati were you able to get a javascript client working?

**Comment by dkati** [comment]
Yes. Simply replace the Date header with
"Request-Date"

**Comment by wizpig64** [comment]
Nice! I'm glad you figured it out :)
